Models/CommanderDeck.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Card_Tracker_v3.Models
{
    public class CommanderDeck
    {
        public int Id { get; set; }
        public string DeckName { get; set; }
        public int? AmountOfCards { get; set; }
        public int MagicGameFormatsId { get; set; }
        public MagicGameFormats MagicGameFormats { get; set; }
        public bool PlayReadyStatus { get; set; }
        public float? Cost { get; set; }
    }
}

ViewModels/UploadDeckViewModel.cs
using Card_Tracker_v3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Card_Tracker_v3.ViewModels
{
    public class UploadDeckViewModel
    {
        public List<DeckLookUp> Cards { get; set; }
        public int DeckId { get; set; }
    }
}

Controllers/CommanderDecksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Card_Tracker_v3.Data;
using Card_Tracker_v3.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Card_Tracker_v3.ViewModels;

namespace Card_Tracker_v3.Controllers
{
    public class CommanderDecksController : Controller
    {
        private readonly TrackerContext _context;

        public CommanderDecksController(TrackerContext context)
        {
            _context = context;
        }

        // GET: CommanderDecks
        public async Task<IActionResult> Index()
        {
            var trackerContext = _context.CommanderDeck.Include(c => c.MagicGameFormats);
            return View(await trackerContext.ToListAsync());
        }

        [HttpPost]
        public IActionResult UploadDeck([Bind("DeckId")]IFormFile file, int DeckId)
        {
            using (var reader = new StreamReader(file.OpenReadStream()))
            {
                int numberOfCards = 0;
                while (reader.Peek() >= 0) {
                    var test = reader.ReadLine();
                    DeckLookUp newCard = new()
                    {
                        CardAmount = Int32.Parse(test.Split(' ')[0]),
                        CardName = test.Split(' ', 2)[1],
                        CommanderDeckId = DeckId, //This is manual for now
                        CardTypeId = 1,
                        LegalityStatus = true
                    };
                    _context.DeckLookUp.Add(newCard);
                    _context.SaveChanges();
                    numberOfCards++;
                }
                var deck = _context.CommanderDeck.Where(x => x.Id == DeckId).SingleOrDefault();
                deck.AmountOfCards = numberOfCards;
                _context.SaveChanges();
            }
            return View();
        }

        // GET: CommanderDecks/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cardList = await _context.DeckLookUp.Where(x => x.CommanderDeckId == id).ToListAsync();
            UploadDeckViewModel viewModel = new()
            {
                Cards = cardList,
                DeckId = id
            };
            if (cardList == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        // GET: CommanderDecks/Create
        public IActionResult Create()
        {
            ViewData["MagicGameFormatsId"] = new SelectList(_context.MagicGameFormats, "Id", "FormatName");
            return View();
        }

        // POST: CommanderDecks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DeckName,AmountOfCards,MagicGameFormatsId,PlayReadyStatus,Cost")] CommanderDeck commanderDeck)
        {
            if (ModelState.IsValid)
            {
                _context.Add(commanderDeck);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MagicGameFormatsId"] = new SelectList(_context.MagicGameFormats, "Id", "Id", commanderDeck.MagicGameFormatsId);
            return View(commanderDeck);
        }

        // GET: CommanderDecks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commanderDeck = await _context.CommanderDeck.FindAsync(id);
            if (commanderDeck == null)
            {
                return NotFound();
            }
            ViewData["MagicGameFormatsId"] = new SelectList(_context.MagicGameFormats, "Id", "Id", commanderDeck.MagicGameFormatsId);
            return View(commanderDeck);
        }

        // POST: CommanderDecks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DeckName,AmountOfCards,MagicGameFormatsId,PlayReadyStatus,Cost")] CommanderDeck commanderDeck)
        {
            if (id != commanderDeck.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(commanderDeck);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommanderDeckExists(commanderDeck.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MagicGameFormatsId"] = new SelectList(_context.MagicGameFormats, "Id", "Id", commanderDeck.MagicGameFormatsId);
            return View(commanderDeck);
        }

        // GET: CommanderDecks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commanderDeck = await _context.CommanderDeck
                .Include(c => c.MagicGameFormats)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (commanderDeck == null)
            {
                return NotFound();
            }

            return View(commanderDeck);
        }

        // POST: CommanderDecks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var commanderDeck = await _context.CommanderDeck.FindAsync(id);
            _context.CommanderDeck.Remove(commanderDeck);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommanderDeckExists(int id)
        {
            return _context.CommanderDeck.Any(e => e.Id == id);
        }
    }
}

Views/CommanderDecks/Create.cshtml
@model Card_Tracker_v3.Models.CommanderDeck

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>CommanderDeck</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DeckName" class="control-label"></label>
                <input asp-for="DeckName" class="form-control" />
                <span asp-validation-for="DeckName" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="AmountOfCards" class="control-label"></label>
                <input asp-for="AmountOfCards" class="form-control" />
                <span asp-validation-for="AmountOfCards" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="MagicGameFormatsId" class="control-label"></label>
                <select asp-for="MagicGameFormatsId" class ="form-control" asp-items="ViewBag.MagicGameFormatsId"></select>
            </div>
            @*<div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="PlayReadyStatus" /> @Html.DisplayNameFor(model => model.PlayReadyStatus)
                </label>
            </div>*@
            @*<div class="form-group">
                <label asp-for="Cost" class="control-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CommanderDecks/Delete.cshtml
@model Card_Tracker_v3.Models.CommanderDeck

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CommanderDeck</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeckName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeckName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AmountOfCards)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AmountOfCards)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MagicGameFormats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MagicGameFormats.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayReadyStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayReadyStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/CommanderDecks/Details.cshtml
@model Card_Tracker_v3.ViewModels.UploadDeckViewModel

@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    int id = Model.DeckId;

}

<h1>Card List</h1>

@using (Html.BeginForm("UploadDeck",
                    "CommanderDecks",
                    FormMethod.Post,
                    new { enctype = "multipart/form-data" }))
{
    <label for="file">Upload Card List:</label>
    <input type="file" name="file" />
    <input class="btn btn-primary" type="submit" />

    <input asp-for="DeckId" type="hidden" value="@id" />

}
<table class="table">
    <thead>
        <tr>
            @*<th>
                    @Html.DisplayNameFor(model => model.CommanderDeck)
                </th>*@
            <th>
                Card Name 
            </th>
            <th>
                # of Cards
            </th>
            <th>
                Legality Status
            </th>
            <th>
                Deck Commander
            </th>
            <th>
                Card Type
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Cards)
        {

            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.CommanderDeckId)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.CardName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CardAmount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LegalityStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.isCommander)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CardType.Id)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/CommanderDecks/Edit.cshtml
@model Card_Tracker_v3.Models.CommanderDeck

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>CommanderDeck</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DeckName" class="control-label"></label>
                <input asp-for="DeckName" class="form-control" />
                <span asp-validation-for="DeckName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AmountOfCards" class="control-label"></label>
                <input asp-for="AmountOfCards" class="form-control" />
                <span asp-validation-for="AmountOfCards" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MagicGameFormatsId" class="control-label"></label>
                <select asp-for="MagicGameFormatsId" class="form-control" asp-items="ViewBag.MagicGameFormatsId"></select>
                <span asp-validation-for="MagicGameFormatsId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="PlayReadyStatus" /> @Html.DisplayNameFor(model => model.PlayReadyStatus)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Cost" class="control-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CommanderDecks/Index.cshtml
@model IEnumerable<Card_Tracker_v3.Models.CommanderDeck>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DeckName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AmountOfCards)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MagicGameFormats)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayReadyStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DeckName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AmountOfCards)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MagicGameFormats.FormatName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlayReadyStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/CommanderDecks/UploadDeck.cshtml
@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>View</h1>